"""
Django settings for _DjangoBackend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bn@6fy3si%dh@3&m_fu99uftq2ct=8$rzxzz60%s+3i#ez4#(c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Add your apps here to enable them
    "daphne",
    'InfrastructureApp.apps.ToolkitAdminConfig', #replaces 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',    # Not required since we started using our own Session Engine.
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'ResearchToolkit apps:
    'ToolkitAdminApp.apps.ToolkitAdminAppConfig',
    'InfrastructureApp.apps.InfrastructureAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_DjangoBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_DjangoBackend.wsgi.application'
ASGI_APPLICATION = "_DjangoBackend.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

SESSION_ENGINE = 'InfrastructureApp.DBSessionEngine'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

#---- Media (user uploaded files) settings ----#
MEDIA_ROOT = BASE_DIR / 'media/'    # used by Djago for FileField downloads
MEDIA_URL = '/media/'    # used by Djago for FileField downloads

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            # setting the location and base_url different from MEDIA_ROOT and MEDIA_URL prevents public unauthenticated access to media files.
            "location": BASE_DIR / 'restricted_media/',
            "base_url": "/restricted_media/",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# <-- FUTURE SCOPE: CUSTOMIZED BACKEND DASHBOARD -->
# LOGIN_URL = "ToolkitAdminApp.ToolkitLoginView"
# LOGIN_REDIRECT_URL = 'Index'
# LOGOUT_REDIRECT_URL = LOGIN_URL
IGNORABLE_404_URLS = [
    re.compile(r"^/favicon\.ico$"),
]

AUTH_USER_MODEL = 'ToolkitAdminApp.User'

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

INTERNAL_IPS = [
    '0.0.0.0',
    '127.0.0.1',
    'localhost',
    ]
ALLOWED_HOSTS = INTERNAL_IPS


# Middleware framework
# https://docs.djangoproject.com/en/2.1/topics/http/middleware/
CONTENT_SECURITY_POLICY_DEFAULT_SOURCES = [
    "https://cdn.jsdelivr.net"
]
MIDDLEWARE = [
    'InfrastructureApp.middleware.NeverCacheMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'InfrastructureApp.middleware.ToolkitSecurityMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Keep ModelBackend around for per-user permissions and maybe a local superuser.
AUTHENTICATION_BACKENDS = [
    # 'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]


