# Generated by Django 4.0.5 on 2022-07-08 02:55

from collections import UserString
from django.db import migrations
import pandas as pd
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.utils import timezone
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from InfrastructureApp.constants import Users
from copy import deepcopy


UserModel = get_user_model()

def loadUsers (apps):
    #Step-1: Get users and groups from previous database.
    defaultDBDictionaryIdentifier = "default"
    previousDBDictionaryIdentifier = "previousDB"
    usersFromPreviousDB = UserModel.objects.using(previousDBDictionaryIdentifier)
    groupsFromPreviousDB = Group.objects.using(previousDBDictionaryIdentifier)

    print("No. of groups from previous database: ", len(groupsFromPreviousDB))


    #Step-2: Group-level migration tasks from previous database:
    #   2.1. Create the required groups
    #   2.2. Create the requisite group-contenttype_permission association

    # for groupFromPreviousDB in groupsFromPreviousDB:
    #     try:    # Case when specified group already exists.
    #         group = Group.objects.get(name = groupFromPreviousDB.name)
    #     except ObjectDoesNotExist: # Case when specified group doesn't exist.
    #         group = Group()
    #         group.name = groupFromPreviousDB.name
    #         group.save()
    #         for groupPermissionFromPreviousDB in groupFromPreviousDB.permissions.all():
    #             permission = Permission.objects.get(codename = groupPermissionFromPreviousDB.codename)
    #             group.permissions.add(permission)

    
    for groupFromPreviousDB in groupsFromPreviousDB:
        groupCopyFromPreviousDB = deepcopy(groupFromPreviousDB)
        groupCopyFromPreviousDB.pk = None
        groupCopyFromPreviousDB.save(using=defaultDBDictionaryIdentifier)
        groupInPresentDB = Group.objects.get(name = groupCopyFromPreviousDB.name)    # you'll be able to add permissions only to object in current databse; not from previous database.
        for groupPermissionFromPreviousDB in groupFromPreviousDB.permissions.all():
            permission = Permission.objects.get(codename = groupPermissionFromPreviousDB.codename)
            groupInPresentDB.permissions.add(permission)
            ## [NOTE:] If this code gives an error that the "Permission doesn't exist", the probable causes would be:
            ##      1. You've created a custom permission, over and above the default 4 (add/change/delete/view) permissions per model created by django.
            ##      2. You have removed a model that was present in the previous release.


    #Step-3: User-level migration tasks from previous database:
    #   3.1. Create the required users
    #   3.2. Create the user-group associations
    try:
        for userFromPreviousDB in usersFromPreviousDB:
            userCopyFromPreviousDB = deepcopy(userFromPreviousDB)
            userCopyFromPreviousDB.pk = None
            userCopyFromPreviousDB.save(using=defaultDBDictionaryIdentifier)
            userInPresentDB = UserModel.objects.get(username = userFromPreviousDB.username)      # you'll be able to add user to a group only if the user object is from the current databse; not from previous database.
            for userGroupFromPreviousDB in userFromPreviousDB.groups.all():
                group = Group.objects.get(name = userGroupFromPreviousDB.name)
                userInPresentDB.groups.add(group)
    except Exception as e:
        pass

    #Step-4: Create a systemroot superuser, if one hasn't been created from the previous database.
    systemRootUsername = Users.RootUser.username
    try:    # Case when systemroot account has been created from the previous database.
        UserModel.objects.get(username = systemRootUsername)
    except ObjectDoesNotExist: # Case when systemroot account hasn't been created from the previous database.
        adminUser = UserModel()
        adminUser.username = systemRootUsername
        adminUser.set_password('Authority@123#')
        adminUser.is_staff = True    
        adminUser.last_login = timezone.now()
        adminUser.is_superuser = True
        adminUser.save(using = defaultDBDictionaryIdentifier)