# Generated by Django 6.0.2 on 2026-03-05 09:27

import ToolkitAdminApp.models.LoginOTPsModel
import ToolkitAdminApp.models.PasswordResetOTPsModel
import ToolkitAdminApp.models.SessionsModel
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("ToolkitAdminApp", "SchemaMigration"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                (
                    "expire_date",
                    models.DateTimeField(db_index=True, verbose_name="expire date"),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "db_table": "django_session",
                "abstract": False,
            },
            managers=[
                ("objects", ToolkitAdminApp.models.SessionsModel.SessionManager()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ToolkitUserSessionRelationships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbEntryCreationDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Entry creation date-time",
                    ),
                ),
                (
                    "dbLastModifiedDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was last modified. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Last Modified date-time",
                    ),
                ),
                (
                    "parentSession",
                    models.OneToOneField(
                        help_text="Select the Session.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toolkitUserSessionRelationshipsParentSession",
                        to="ToolkitAdminApp.sessions",
                        verbose_name="SESSION",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CREATED BY (USER)",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sModifiedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="MODIFIED BY (USER)",
                    ),
                ),
                (
                    "parentUser",
                    models.OneToOneField(
                        help_text="Select the user.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="toolkitUserSessionRelationshipsParentUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="USER",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toolkit User Session Relationship",
                "verbose_name_plural": "Toolkit User Session Relationships",
                "ordering": ["parentUser"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTPs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbEntryCreationDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Entry creation date-time",
                    ),
                ),
                (
                    "dbLastModifiedDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was last modified. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Last Modified date-time",
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        help_text="One-time password.",
                        max_length=16,
                        unique=True,
                        verbose_name="ONE-TIME PASSWORD",
                    ),
                ),
                (
                    "validTillDateTime",
                    models.DateTimeField(
                        default=ToolkitAdminApp.models.PasswordResetOTPsModel.tenMinutesDelayedDateTime,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="VALID TILL DATE-TIME",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CREATED BY (USER)",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sModifiedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="MODIFIED BY (USER)",
                    ),
                ),
                (
                    "referencedUser",
                    models.OneToOneField(
                        help_text="Select the user for the following password reset OTP.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="passwordResetOTPsReferencedUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="USER",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "ordering": ["referencedUser"],
            },
        ),
        migrations.CreateModel(
            name="LoginOTPs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbEntryCreationDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Entry creation date-time",
                    ),
                ),
                (
                    "dbLastModifiedDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was last modified. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Last Modified date-time",
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        help_text="One-time password.",
                        max_length=16,
                        unique=True,
                        verbose_name="ONE-TIME PASSWORD",
                    ),
                ),
                (
                    "validTillDateTime",
                    models.DateTimeField(
                        default=ToolkitAdminApp.models.LoginOTPsModel.tenMinutesDelayedDateTime,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="VALID TILL DATE-TIME",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CREATED BY (USER)",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sModifiedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="MODIFIED BY (USER)",
                    ),
                ),
                (
                    "referencedUser",
                    models.OneToOneField(
                        help_text="Select the user for the following password reset OTP.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="loginOTPsReferencedUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="USER",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login OTP",
                "verbose_name_plural": "Login OTPs",
                "ordering": ["referencedUser"],
            },
        ),
        migrations.CreateModel(
            name="InvalidLoginCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbEntryCreationDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Entry creation date-time",
                    ),
                ),
                (
                    "dbLastModifiedDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was last modified. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Last Modified date-time",
                    ),
                ),
                (
                    "invalidLoginCounter",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of invalid login attempts (max 5).",
                        validators=[
                            django.core.validators.MaxValueValidator(limit_value=5)
                        ],
                        verbose_name="INVALID LOGIN COUNTER",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CREATED BY (USER)",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sModifiedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="MODIFIED BY (USER)",
                    ),
                ),
                (
                    "parentUser",
                    models.OneToOneField(
                        help_text="Select the user for which Invalid Login Counter is to be set.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invalidLoginCounterReferencedUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="USER",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invalid Login Counter",
                "verbose_name_plural": "Invalid Login Counters",
                "ordering": ["parentUser"],
            },
        ),
        migrations.CreateModel(
            name="UserEquivalences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbEntryCreationDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Entry creation date-time",
                    ),
                ),
                (
                    "dbLastModifiedDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was last modified. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Last Modified date-time",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CREATED BY (USER)",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sModifiedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="MODIFIED BY (USER)",
                    ),
                ),
                (
                    "referencedEquivalentUser",
                    models.ForeignKey(
                        help_text="Select the user who is to become equivalent to the original user. This user will henceforth have access to the objects created/modifed by the Original User.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="userEquivalencesReferencedEquivalentUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="EQUIVALENT USER",
                    ),
                ),
                (
                    "referencedOriginalUser",
                    models.ForeignKey(
                        help_text="Select the user to whom the Equivalent User is to be equated to.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="userEquivalencesReferencedOriginalUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ORIGINAL USER",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Equivalence",
                "verbose_name_plural": "User Equivalences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("referencedOriginalUser", "referencedEquivalentUser"),
                        name="unique_OriginalUser_EquivalentUser_UserEquivalences_Relationship",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreviousPasswordHashes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbEntryCreationDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was created. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Entry creation date-time",
                    ),
                ),
                (
                    "dbLastModifiedDateTime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="This is the date-time when this entry was last modified. It's supposed to be system-generated and non-modifiable by any user.",
                        verbose_name="Last Modified date-time",
                    ),
                ),
                (
                    "passwordHash",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CREATED BY (USER)",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s%(class)sModifiedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="MODIFIED BY (USER)",
                    ),
                ),
                (
                    "referencedUser",
                    models.ForeignKey(
                        help_text="Select the user to whom the Equivalent User is to be equated to.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="previousPasswordHashesReferencedUser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="REFERENCED USER",
                    ),
                ),
            ],
            options={
                "verbose_name": "Previous Password Hash",
                "verbose_name_plural": "Previous Password Hashes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("referencedUser", "passwordHash"),
                        name="unique_User_PasswordHash_PreviousPasswordHashes_Relationship",
                    )
                ],
            },
        ),
    ]
